using UnityEngine;

public class RollDiceButton : MonoBehaviour
{
    public Outline outline;

    public GameRuleMaster ruleMaster;

    public DiceMachine diceMachine;

    public Transform playerTransform;

    public Transform rollcubeTransform;

    public int RollNum = 5;
    public bool noRolls = false;

    void Start()
    {
        outline = GetComponent<Outline>();
        outline.enabled = false;

        rollcubeTransform = GetComponent<Transform>();

        if (playerTransform == null)
        {
            GameObject playerObj = GameObject.FindGameObjectWithTag("Player");
            if (playerObj != null)
            {
                playerTransform = playerObj.transform;
            }
        }
    }

    void Update()
    {
        if (playerTransform != null)
        {
            rollcubeTransform.position = playerTransform.position + new Vector3(3f, 7f, 0f);
        }
    }

    void OnMouseDown()
    {
        if (!ruleMaster.isAttacking)
        {
            if (diceMachine.IsRolling || RollNum > -1)
            {
                Debug.Log("Rolling is Start, RollNUM : " + RollNum);
                diceMachine.ToggleDiceState();
            }
            else
            {
                noRolls = true;
                Debug.Log("No rolls left!");
            }
        }
    }

    private void OnMouseEnter()
    {
        outline.enabled = true;
    }

    private void OnMouseExit()
    {
        outline.enabled = false;
    }
}